name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Setup project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node v12.8.1
        uses: actions/setup-node@master
        with:
          node-version: '12.8.1'

      - name: Clean install dependencies
        run: npm ci

      - name: Fix possible linting problems
        run: npm run lint

      - name: Build for production
        run: npm run build
